### PR TITLE
[MF-4] Added an explanation component

### PR DESCRIPTION
**Pull request by Ayush-Gopisetty**
* **Please check if the PR fulfills these requirements**
- [ ] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
The change that this PR introduces is that the PR adds an explanation component that will give a quick introduction about the project and explains what the project will do.

* **What is the current behavior?What does the code do before you made the new changes?** 
The current behavior is that the explanation component will show up instead of the message "Hello World" showing up when I run the application. Before I made changes the changes the code only showed the message "Hello World" when the application ran.

* **What is the new behavior?**
The new behavior is that the application will show the explanation component, which will give a brief introduction of the application and will explain what the application will do.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
This PR does not really introduce a breaking change but I did have to adjust the LandingPage.js file in order to get the component to show up when running the application. Even though I had to adjust the LandingPage.js file, the users will not need to make any changes in their application due to the PR. Also, the users will not need to run a new command as a result of this PR.

* **Other information**:

### CODE REVIEW

**Review by tqyn117 — COMMENTED** [review]
The import for App.js seems unnecessary.

**Review by Codubee — APPROVED** [review]
LGTM!

**Review by rng190001 — APPROVED** [review]
good to go!

**Review by JocelynHeckenkamp — APPROVED** [review]
Good!

**Review by tqyn117 — APPROVED** [review]

**Pull request merged**
